### ISSUE TITLE
Typo in failure pop-up

### ISSUE THREAD

**Issue by fossum** [perljedi/atom-perl-prove#1]
![image](https://cloud.githubusercontent.com/assets/448582/12280670/a9528d50-b944-11e5-9d19-2e93f742e1c7.png)

Plugin version: 0.5.0
Atom Version: 1.3.3

**Comment by perljedi** [comment]
Thank you for the report, I'll correct that immediately.

**Comment by perljedi** [comment]
This has been corrected in version 0.5.1.

**Comment by fossum** [comment]
Excellent response speed 5 out of 5 stars :+1:

**Comment by fossum** [comment]
Hmm... this doesn't look fixed for me. I updated to 0.5.1 and I still have the same typo.
